### ISSUE TITLE
ios AppDelegate.swift配置问题

### ISSUE THREAD

**Issue by zhuxiwen** [best-flutter/flutter_alipay#12]
* mac 10.15.1
* Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
* Framework • revision 27321ebbad (7 days ago) • 2019-12-10 18:15:01 -0800
* Engine • revision 2994f7e1e6
* Tools • Dart 2.7.0
-------------------------
看https://pub.dev/packages/flutter_alipay 教程里的swift配置和我默认配置是不一样的，是在我的默认基本上改，还是后面加上就好了？如果不是能给个正确版本吗或更新教程中的swift例子，谢谢

![Image text](https://dev-img.oss-cn-shanghai.aliyuncs.com/u9mumKomBVDD0lVieZPI.jpg)

**Comment by xieguangya** [comment]
本人Android开发，摸索了很久，iOS这里需要添加https的配置，不然会报6002，然后创建一个文件，通过扩展的方式添加上面的代码，终于OK了，附上代码：
extension AppDelegate{
    // iOS 9 以上请用这个
    override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any]) -> Bool {
        return FlutterAlipayPlugin.handleOpen(url);
    }
}

**Comment by xieguangya** [comment]
本人Android开发，摸索了很久，iOS这里需要添加https的配置，不然会报6002，然后调起支付宝app支付的时候收不到回调，最后通过扩展AppDelegate的方式解决了，附上代码：
extension AppDelegate{
    // iOS 9 以上请用这个
    override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any]) -> Bool {
        return FlutterAlipayPlugin.handleOpen(url);
    }
}

**Comment by zhuxiwen** [comment]
大哥，天秀，我搞成功了！！

**Comment by zhuxiwen** [comment]
@xieguangya

**Comment by zhuxiwen** [comment]
![image](https://user-images.githubusercontent.com/19161200/78748394-887e6580-799e-11ea-8cdb-501261597b91.png)
![image](https://user-images.githubusercontent.com/19161200/78748410-92a06400-799e-11ea-8293-3897f525d763.png)
还有info.plist中的配置按https://www.cnblogs.com/hacjy/p/5138652.html中的来，希望能帮到后来遇到这个问题的朋友们
