### ISSUE TITLE
flutter 更新到v1.12.13+hotfix.5后 release报错

### ISSUE THREAD

**Issue by leoyfj** [best-flutter/flutter_alipay#13]
![TIM图片20200108094412](https://user-images.githubusercontent.com/4299360/71943381-76542600-31fb-11ea-8ed0-4ce903cb2362.png)
![TIM截图20200108094448](https://user-images.githubusercontent.com/4299360/71943414-9257c780-31fb-11ea-839a-9b89598eb194.png)

麻烦修复一下

**Comment by gaojuanjuan** [comment]
> ![TIM图片20200108094412](https://user-images.githubusercontent.com/4299360/71943381-76542600-31fb-11ea-8ed0-4ce903cb2362.png)
> ![TIM截图20200108094448](https://user-images.githubusercontent.com/4299360/71943414-9257c780-31fb-11ea-839a-9b89598eb194.png)
> 
> 麻烦修复一下

我也遇到了这个问题，请问你解决了吗？
