### ISSUE TITLE
我在ios13上调用支付宝成功后，不能收到支付宝的回调

### ISSUE THREAD

**Issue by aohanhe** [best-flutter/flutter_alipay#17]
问题如题，请问有什么方法解决这个问题，我加上这两个方法，通过xcode监听都没有收到回调
  override func application(_ application: UIApplication, handleOpen url: URL) -> Bool {
        return FlutterAlipayPlugin.handleOpen(url);
  }

  override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        return FlutterAlipayPlugin.handleOpen(url);
  }

**Comment by kobewang** [comment]
问题同上，估计作者没空解决，换了个插件 ibatis 可以收到回调，参考[https://www.cnblogs.com/kobewang/p/12780981.html](url)
