### ISSUE TITLE
FlutterAlipay.pay的_payInfo是什么格式。

### ISSUE THREAD

**Issue by sidealice** [best-flutter/flutter_alipay#2]
没找到sample，是调用app接口吗。

_payInfo是我们平时签名以后提交给支付宝的那个数据结果吗？

**Comment by sidealice** [comment]
alipay.trade.app.pay 这个接口对吗？

**Comment by sidealice** [comment]
您好，我想请教下，你的这个接口是手机网站接口对吗，并没有调用native的客户端发起交易？
我在用alipay.trade.app.pay这个接口的返回数据进行支付以后，返回的是支付宝手机网站h5的页面。

**Comment by jzoom** [comment]
可以调起支付宝客户端支付

**Comment by sidealice** [comment]
请教，有没有最简sample文件可以运行下?
我按照隔壁wechat微信支付的也没跑起来，隔壁的微信客户端调用起来了。

**Comment by jzoom** [comment]
_payInfo 是个字符串,类似这种
![image](https://user-images.githubusercontent.com/6038236/44098192-19f98e94-a012-11e8-82f6-4b80bb7496b3.png)

**Comment by sidealice** [comment]
app_id=xxxx&method=alipay.trade.app.pay&charset=utf-8&sign_type=RSA2&timestamp=2018-08-15+19%3A50%3A05&version=1.0&notify_url=xxxxxx&biz_content=%7B%22out_trade_no%22%3A%22000000215%22%2C%22product_code%22%3A%22QUICK_MSECURITY_PAY%22%2C%22subject%22%3A%22CosplayQ-%5Cu670d%5Cu88c5%22%2C%22body%22%3A%22CosplayQ-%5Cu670d%5Cu88c5%22%2C%22total_amount%22%3A%22108.00%22%7D&sign=sVv4R%2ByDUPQ1D6h7%2FtJdJG9rTdjZi7%2BcFEwPccZJ%2F2EODimbqCZfCTihuvUalOHQxBi7aJrERPGawVlZzkJ%2BJkxe4FrVxtvqQmiwu41vvufisif0zK2ehwciBdjiee7qtyXpUr8sSez7dPVnCVbKcX5No%2BtB6CuZWxzTXrE5lkAXvRd6XTQXAs3p2%2FPP9FsbEQhXOGzDiKEA0oFIE2XLHO2R1vOy0zgkyZn35A25e0f4GXamJ76kydHSe0%2BWzi68R70Rbgcc539tN43f2BLWLBGTPft1bAMKeptmQBCxrwciYy%2BVR%2BjTF%2BKV88ToEj77Xup9RVAgJDfxojlq%2F4GBGg%3D%3D


你用的是mobile.securitypay.pay，是否是因为是老的接口可以用native，你用alipay.trade.app.pay的方式可以吗

**Comment by jzoom** [comment]
我这边确实是老接口，新接口我试下，代码已经更新，现在可以调用，接口上到了外网，你可以试下。

**Comment by sidealice** [comment]
现在可以调用的到native 支付宝了。谢谢
